### ISSUE TITLE
Compile errors when we integrate backtrace using Pod.

### ISSUE THREAD

**Issue by Nookaraju** [backtrace-labs/backtrace-cocoa#37]
<img width="1049" alt="Screenshot 2020-07-15 at 4 34 40 PM" src="https://user-images.githubusercontent.com/2161122/87538046-3a71b000-c6b9-11ea-8b3d-d64cd36ad9a0.png">

It throws 2 errors while running the with backtrace lib integrated in the app via pod.

**Comment by Nookaraju** [comment]
@krml19 can please check this issue?

**Comment by krml19** [comment]
Hi @Nookaraju, thanks for reporting this issue. 
I believe this issue only affects projects running on Swift 5.x version. I'll definitely have a look into that and this will be fixed in next release.

As a quick workaround, I'd suggest to downgrade your project to Swift 4.2 if that's possible.

**Comment by Nookaraju** [comment]
@krml19 I cannot downgrade as our project have other swift 5.x dependencies.
