### ISSUE TITLE
BluetoothStatusListener causes App store submission to require usage description

### ISSUE THREAD

**Issue by michael75431** [backtrace-labs/backtrace-cocoa#53]
This file imports CoreBluetooth and uses CBCentralManager, CBCentralManagerDelegate and CBCentralManagerOptionShowPowerAlertKey.

While the framework doesn't ever reference BluetoothStatusListener, its built as part of the target by default and appears to trigger Apple to ask for the following upon app store submission :

NSBluetoothPeripheralUsageDescription
NSBluetoothAlwaysUsageDescription

It would be preferable to unlink the file from the target (or remove the file if it isn't used or necessary).

**Comment by konraddysput** [comment]
Hey @michael75431 sorry to hear that. 

Our team is reviewing possible solution to this issue and will update ticket soon. You can expect more updates on our side soon!

Thanks!
