### ISSUE TITLE
Question regarding attributes

### ISSUE THREAD

**Issue by schmidt9** [backtrace-labs/backtrace-cocoa#66]
> You can add custom attributes that should be send alongside crash and errors/exceptions
(https://github.com/backtrace-labs/backtrace-cocoa#attributes-)

Do attributes get saved for possible future crashes (ie if a crash occurs they will be saved) or do they get attached to current crash reports that are going to be sent? 

Are attributes the only way to attach custom runtime data? For instance console output?

**Comment by konraddysput** [comment]
hi @schmidt9 
we're storing attributes when a crash occurred. Crash attributes are associated to crash. 

You can also attach runtime data via attachments.

**Comment by schmidt9** [comment]
@konraddysput thanks
