### ISSUE TITLE
Question: addBreadcrumb like in backtrace-labs/backtrace-android

### ISSUE THREAD

**Issue by andreivictor-gumi** [backtrace-labs/backtrace-cocoa#68]
Hello. I'm evaluating Backtrace tech and trying to integrate Backtrace in our C++ iOS/Android game and wrapping each backtrace in a unified Wrapper API for our game in C++. I am wondering where is the equivalent of Android's **addBreadcrumb** in iOS cocoa that will show up also in the Backtrace Dashboard?

Any guidance is appreciated.

**Comment by vlussenburg** [comment]
Hi @andreivictor-gumi,

If you would like to be notified when this is done, could you file a ticket at support.backtrace.io?

Thanks!
Vincent
